services:
  user-service:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: support-storage-service
    ports:
      - "8090:8080"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/appdb
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: support-storage-db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:
