version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: support-storage-service
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
