[tool.ruff]
line-length = 88
select = ["E", "F", "I", "B", "C", "D", "RUF"]
ignore = []
exclude = ["venv", ".git", "__pycache__"]

# Tri des imports (remplace isort)
force-single-line = false
order-by-type = true
combine-as-imports = true
sections = ["STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
default-section = "THIRDPARTY"
known-first-party = ["src"]


[tool.poetry.dependencies]
python = "^3.12"
pylint = ">=3.2,<3.3"
astroid = ">=3.2,<3.3"