# -------------------
# 1. Builder stage
# -------------------
FROM python:3.12-slim AS builder

WORKDIR /app

# Install build tools (only in builder)
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    python3-dev \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Copy requirements and install into /install (isolated layer)
COPY requirements.txt .
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    python3-dev \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*



# -------------------
# 2. Runtime stage
# -------------------
FROM python:3.13-slim AS runtime

WORKDIR /app

# Install only runtime deps (no compiler)
RUN apt-get update && apt-get install -y --no-install-recommends \
    libpq5 \
    && rm -rf /var/lib/apt/lists/*

# Copy only installed packages from builder
COPY --from=builder /install /usr/local

# Copy application code
COPY ./src .

# Expose port
EXPOSE 8080

# Run with Gunicorn + Uvicorn workers
CMD ["gunicorn", "-k", "uvicorn.workers.UvicornWorker", "app:app", "--bind", "0.0.0.0:8080", "--workers", "4", "--threads", "8", "--timeout", "120"]
