name: Run delete Blob (manual)

on:
  workflow_dispatch:   # Permet de lancer manuellement

jobs:

  terraform-destroy-blob:

    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7
      - name: Export Azure Service Principal creds for Terraform
        run: |
          echo "ARM_CLIENT_ID=${{ fromJSON(secrets.AZURE_CREDENTIALS).clientId }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=${{ fromJSON(secrets.AZURE_CREDENTIALS).clientSecret }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ fromJSON(secrets.AZURE_CREDENTIALS).subscriptionId }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ fromJSON(secrets.AZURE_CREDENTIALS).tenantId }}" >> $GITHUB_ENV
          echo  'CONSUL_HTTP_ADDR: "http://37.59.113.68:8500"'

      - name: Destroy VM
        working-directory: terraform
        run: |
          ls
          terraform init -backend-config="path=terraform/${{ github.actor }}/blob"
          terraform destroy  -auto-approve 